package com.postrofit.backend;

import com.postrofit.backend.Bean.MakeOrderBean;
import com.postrofit.backend.Bean.MakeStoreBean;
import com.postrofit.backend.Bean.TakeOrderBean;
import com.postrofit.backend.Model.DAO.*;
import com.postrofit.backend.Model.DTO.RequestMakeOrderDTO;
import com.postrofit.backend.Model.DTO.RequestStoreDTO;
import com.postrofit.backend.Model.DTO.RequestTakeOrderDTO;
import com.postrofit.backend.Model.Enum.OrderStat;
import com.postrofit.backend.Model.Enum.StorageBrand;
import com.postrofit.backend.Model.Enum.StorageSize;
import com.postrofit.backend.Model.Enum.StorageStat;
import com.postrofit.backend.Repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.LocalDate;

@Component
@RequiredArgsConstructor
public class InitDB {

    private final InitService initService;



    @PostConstruct
    public void init(){
        initService.dbInit();
    }


    @Component
    @RequiredArgsConstructor
    static class InitService {
        private final StationDAORepository stationDAORepository;
        private final UserDAORepository userDAORepository;
        private final StoragePasswordDAORepository storagePasswordDAORepository;
        private final StorageDAORepository storageDAORepository;
        private final OrderDAORepository orderDAORepository;
        private final DeliveryDAORepository deliveryDAORepository;
        private final StoreDAORepository storeDAORepository;
        private final MakeOrderBean makeOrderBean;
        private final TakeOrderBean takeOrderBean;
        private final MakeStoreBean makeStoreBean;


        public void dbInit() {
            StationDAO station0 = new StationDAO(0, "테스트역0", StorageBrand.SAENU);
            StationDAO station1 = new StationDAO(1, "테스트역1", StorageBrand.SAENU);
            StationDAO station2 = new StationDAO(2, "테스트역2", StorageBrand.SAENU);
            StationDAO station3 = new StationDAO(3, "테스트역3", StorageBrand.SAENU);

            stationDAORepository.save(station0);
            stationDAORepository.save(station1);
            stationDAORepository.save(station2);
            stationDAORepository.save(station3);

            UserDAO user1 = new UserDAO(0, "마로아님");
            UserDAO user2 = new UserDAO(1, "마로임");
            UserDAO user3 = new UserDAO(2, "배달부1");
            UserDAO user4 = new UserDAO(3, "마로3");
            UserDAO user5 = new UserDAO(4, "마로4");
            UserDAO user6 = new UserDAO(5, "마로5");

            userDAORepository.save(user1);
            userDAORepository.save(user2);
            userDAORepository.save(user3);
            userDAORepository.save(user4);
            userDAORepository.save(user5);
            userDAORepository.save(user6);

            StoragePasswordDAO storagePassword1 = new StoragePasswordDAO(0, "1234");
            StoragePasswordDAO storagePassword2 = new StoragePasswordDAO(1, "5678");
            StoragePasswordDAO storagePassword3 = new StoragePasswordDAO(2, "4945");
            StoragePasswordDAO storagePassword4 = new StoragePasswordDAO(3, "1129");
            StoragePasswordDAO storagePassword5 = new StoragePasswordDAO(4, "1212");
            StoragePasswordDAO storagePassword6 = new StoragePasswordDAO(5, "1313");
            StoragePasswordDAO storagePassword7 = new StoragePasswordDAO(6, "1414");
            StoragePasswordDAO storagePassword8 = new StoragePasswordDAO(7, "1515");
            StoragePasswordDAO storagePassword9 = new StoragePasswordDAO(8, "1616");
            StoragePasswordDAO storagePassword10 = new StoragePasswordDAO(9, "1717");
            StoragePasswordDAO storagePassword11 = new StoragePasswordDAO(10, "1188");
            StoragePasswordDAO storagePassword12 = new StoragePasswordDAO(11, "1122");
            StoragePasswordDAO storagePassword13 = new StoragePasswordDAO(12, "1111");
            StoragePasswordDAO storagePassword14 = new StoragePasswordDAO(13, "2232");
            StoragePasswordDAO storagePassword15 = new StoragePasswordDAO(14, "2242");
            StoragePasswordDAO storagePassword16 = new StoragePasswordDAO(15, "2252");
            StoragePasswordDAO storagePassword17 = new StoragePasswordDAO(16, "2262");
            StoragePasswordDAO storagePassword18 = new StoragePasswordDAO(17, "2272");
            StoragePasswordDAO storagePassword19 = new StoragePasswordDAO(18, "2282");
            StoragePasswordDAO storagePassword20 = new StoragePasswordDAO(19, "2292");
            StoragePasswordDAO storagePassword21 = new StoragePasswordDAO(20, "2322");
            StoragePasswordDAO storagePassword22 = new StoragePasswordDAO(21, "2422");
            StoragePasswordDAO storagePassword23 = new StoragePasswordDAO(22, "2522");
            StoragePasswordDAO storagePassword24 = new StoragePasswordDAO(23, "2622");
            StoragePasswordDAO storagePassword25 = new StoragePasswordDAO(24, "2722");
            StoragePasswordDAO storagePassword26 = new StoragePasswordDAO(25, "2822");
            StoragePasswordDAO storagePassword27 = new StoragePasswordDAO(26, "2922");
            StoragePasswordDAO storagePassword28 = new StoragePasswordDAO(27, "2022");
            StoragePasswordDAO storagePassword29 = new StoragePasswordDAO(28, "1222");
            StoragePasswordDAO storagePassword30 = new StoragePasswordDAO(29, "2222");
            StoragePasswordDAO storagePassword31 = new StoragePasswordDAO(30, "3222");
            StoragePasswordDAO storagePassword32 = new StoragePasswordDAO(31, "4222");
            StoragePasswordDAO storagePassword33 = new StoragePasswordDAO(32, "5222");
            StoragePasswordDAO storagePassword34 = new StoragePasswordDAO(34, "6222");
            StoragePasswordDAO storagePassword35 = new StoragePasswordDAO(35, "7222");
            StoragePasswordDAO storagePassword36 = new StoragePasswordDAO(36, "8222");
            StoragePasswordDAO storagePassword37 = new StoragePasswordDAO(37, "9222");
            StoragePasswordDAO storagePassword38 = new StoragePasswordDAO(38, "0222");
            StoragePasswordDAO storagePassword39 = new StoragePasswordDAO(39, "2232");
            StoragePasswordDAO storagePassword40 = new StoragePasswordDAO(40, "2452");
            StoragePasswordDAO storagePassword41 = new StoragePasswordDAO(41, "2232");
            StoragePasswordDAO storagePassword42 = new StoragePasswordDAO(42, "2223");
            StoragePasswordDAO storagePassword43 = new StoragePasswordDAO(43, "2224");
            StoragePasswordDAO storagePassword44 = new StoragePasswordDAO(44, "2225");
            StoragePasswordDAO storagePassword45 = new StoragePasswordDAO(45, "2226");
            StoragePasswordDAO storagePassword46 = new StoragePasswordDAO(46, "2227");
            StoragePasswordDAO storagePassword47 = new StoragePasswordDAO(47, "2228");
            StoragePasswordDAO storagePassword48 = new StoragePasswordDAO(48, "2229");
            StoragePasswordDAO storagePassword49 = new StoragePasswordDAO(49, "2902");
            StoragePasswordDAO storagePassword50 = new StoragePasswordDAO(50, "7788");
            StoragePasswordDAO storagePassword51 = new StoragePasswordDAO(51, "1111");
            StoragePasswordDAO storagePassword52 = new StoragePasswordDAO(52, "1111");
            StoragePasswordDAO storagePassword53 = new StoragePasswordDAO(53, "1111");
            StoragePasswordDAO storagePassword54 = new StoragePasswordDAO(54, "1111");
            StoragePasswordDAO storagePassword55 = new StoragePasswordDAO(55, "1111");
            StoragePasswordDAO storagePassword56 = new StoragePasswordDAO(56, "1111");
            StoragePasswordDAO storagePassword57 = new StoragePasswordDAO(57, "1111");
            StoragePasswordDAO storagePassword58 = new StoragePasswordDAO(58, "1111");
            StoragePasswordDAO storagePassword59 = new StoragePasswordDAO(59, "1111");
            StoragePasswordDAO storagePassword60 = new StoragePasswordDAO(60, "1111");
            StoragePasswordDAO storagePassword61 = new StoragePasswordDAO(61, "1111");
            StoragePasswordDAO storagePassword62 = new StoragePasswordDAO(62, "1111");
            StoragePasswordDAO storagePassword63 = new StoragePasswordDAO(63, "1111");
            StoragePasswordDAO storagePassword64 = new StoragePasswordDAO(64, "1111");
            StoragePasswordDAO storagePassword65 = new StoragePasswordDAO(65, "1111");
            StoragePasswordDAO storagePassword66 = new StoragePasswordDAO(66, "1111");
            StoragePasswordDAO storagePassword67 = new StoragePasswordDAO(67, "1111");
            StoragePasswordDAO storagePassword68 = new StoragePasswordDAO(68, "1111");
            StoragePasswordDAO storagePassword69 = new StoragePasswordDAO(69, "1111");
            StoragePasswordDAO storagePassword70 = new StoragePasswordDAO(70, "1111");
            StoragePasswordDAO storagePassword71 = new StoragePasswordDAO(71, "1111");
            StoragePasswordDAO storagePassword72 = new StoragePasswordDAO(72, "1111");
            StoragePasswordDAO storagePassword73 = new StoragePasswordDAO(73, "1111");
            StoragePasswordDAO storagePassword74 = new StoragePasswordDAO(74, "1111");
            StoragePasswordDAO storagePassword75 = new StoragePasswordDAO(75, "1111");
            StoragePasswordDAO storagePassword76 = new StoragePasswordDAO(76, "1111");
            StoragePasswordDAO storagePassword77 = new StoragePasswordDAO(77, "1111");
            StoragePasswordDAO storagePassword78 = new StoragePasswordDAO(78, "1111");
            StoragePasswordDAO storagePassword79 = new StoragePasswordDAO(79, "1111");
            StoragePasswordDAO storagePassword80 = new StoragePasswordDAO(80, "1111");

            storagePasswordDAORepository.save(storagePassword1);
            storagePasswordDAORepository.save(storagePassword2);
            storagePasswordDAORepository.save(storagePassword3);
            storagePasswordDAORepository.save(storagePassword4);
            storagePasswordDAORepository.save(storagePassword5);
            storagePasswordDAORepository.save(storagePassword6);
            storagePasswordDAORepository.save(storagePassword7);
            storagePasswordDAORepository.save(storagePassword8);
            storagePasswordDAORepository.save(storagePassword9);
            storagePasswordDAORepository.save(storagePassword10);
            storagePasswordDAORepository.save(storagePassword11);
            storagePasswordDAORepository.save(storagePassword12);
            storagePasswordDAORepository.save(storagePassword13);
            storagePasswordDAORepository.save(storagePassword14);
            storagePasswordDAORepository.save(storagePassword15);
            storagePasswordDAORepository.save(storagePassword16);
            storagePasswordDAORepository.save(storagePassword17);
            storagePasswordDAORepository.save(storagePassword18);
            storagePasswordDAORepository.save(storagePassword19);
            storagePasswordDAORepository.save(storagePassword20);
            storagePasswordDAORepository.save(storagePassword21);
            storagePasswordDAORepository.save(storagePassword22);
            storagePasswordDAORepository.save(storagePassword23);
            storagePasswordDAORepository.save(storagePassword24);
            storagePasswordDAORepository.save(storagePassword25);
            storagePasswordDAORepository.save(storagePassword26);
            storagePasswordDAORepository.save(storagePassword27);
            storagePasswordDAORepository.save(storagePassword28);
            storagePasswordDAORepository.save(storagePassword29);
            storagePasswordDAORepository.save(storagePassword30);
            storagePasswordDAORepository.save(storagePassword31);
            storagePasswordDAORepository.save(storagePassword32);
            storagePasswordDAORepository.save(storagePassword33);
            storagePasswordDAORepository.save(storagePassword34);
            storagePasswordDAORepository.save(storagePassword35);
            storagePasswordDAORepository.save(storagePassword36);
            storagePasswordDAORepository.save(storagePassword37);
            storagePasswordDAORepository.save(storagePassword38);
            storagePasswordDAORepository.save(storagePassword39);
            storagePasswordDAORepository.save(storagePassword40);
            storagePasswordDAORepository.save(storagePassword41);
            storagePasswordDAORepository.save(storagePassword42);
            storagePasswordDAORepository.save(storagePassword43);
            storagePasswordDAORepository.save(storagePassword44);
            storagePasswordDAORepository.save(storagePassword45);
            storagePasswordDAORepository.save(storagePassword46);
            storagePasswordDAORepository.save(storagePassword47);
            storagePasswordDAORepository.save(storagePassword48);
            storagePasswordDAORepository.save(storagePassword49);
            storagePasswordDAORepository.save(storagePassword50);
            storagePasswordDAORepository.save(storagePassword51);
            storagePasswordDAORepository.save(storagePassword52);
            storagePasswordDAORepository.save(storagePassword53);
            storagePasswordDAORepository.save(storagePassword54);
            storagePasswordDAORepository.save(storagePassword55);
            storagePasswordDAORepository.save(storagePassword56);
            storagePasswordDAORepository.save(storagePassword57);
            storagePasswordDAORepository.save(storagePassword58);
            storagePasswordDAORepository.save(storagePassword59);
            storagePasswordDAORepository.save(storagePassword60);
            storagePasswordDAORepository.save(storagePassword61);
            storagePasswordDAORepository.save(storagePassword62);
            storagePasswordDAORepository.save(storagePassword63);
            storagePasswordDAORepository.save(storagePassword64);
            storagePasswordDAORepository.save(storagePassword65);
            storagePasswordDAORepository.save(storagePassword66);
            storagePasswordDAORepository.save(storagePassword67);
            storagePasswordDAORepository.save(storagePassword68);
            storagePasswordDAORepository.save(storagePassword69);
            storagePasswordDAORepository.save(storagePassword70);
            storagePasswordDAORepository.save(storagePassword71);
            storagePasswordDAORepository.save(storagePassword72);
            storagePasswordDAORepository.save(storagePassword73);
            storagePasswordDAORepository.save(storagePassword74);
            storagePasswordDAORepository.save(storagePassword75);
            storagePasswordDAORepository.save(storagePassword76);
            storagePasswordDAORepository.save(storagePassword77);
            storagePasswordDAORepository.save(storagePassword78);
            storagePasswordDAORepository.save(storagePassword79);
            storagePasswordDAORepository.save(storagePassword80);

            StorageDAO storage1 = new StorageDAO(0, station0.getStationId(), storagePassword1.getStoragePasswordId(), 1, StorageStat.EMPTY,  new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage2 = new StorageDAO(1, station0.getStationId(), storagePassword2.getStoragePasswordId(), 2, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage3 = new StorageDAO(2, station0.getStationId(), storagePassword3.getStoragePasswordId(), 3, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage4 = new StorageDAO(3, station0.getStationId(), storagePassword4.getStoragePasswordId(), 4, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage5 = new StorageDAO(4, station0.getStationId(), storagePassword5.getStoragePasswordId(), 5, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage6 = new StorageDAO(5, station0.getStationId(), storagePassword6.getStoragePasswordId(), 6, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage7 = new StorageDAO(6, station0.getStationId(), storagePassword7.getStoragePasswordId(), 7, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage8 = new StorageDAO(7, station0.getStationId(), storagePassword8.getStoragePasswordId(), 8, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage9 = new StorageDAO(8, station0.getStationId(), storagePassword9.getStoragePasswordId(), 9, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage10 = new StorageDAO(9, station0.getStationId(), storagePassword10.getStoragePasswordId(), 10, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage11 = new StorageDAO(10, station0.getStationId(), storagePassword11.getStoragePasswordId(), 11, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage12 = new StorageDAO(11, station0.getStationId(), storagePassword12.getStoragePasswordId(), 12, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage13 = new StorageDAO(12, station0.getStationId(), storagePassword13.getStoragePasswordId(), 13, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage14 = new StorageDAO(13, station0.getStationId(), storagePassword14.getStoragePasswordId(), 14, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage15 = new StorageDAO(14, station0.getStationId(), storagePassword15.getStoragePasswordId(), 15, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage16 = new StorageDAO(15, station0.getStationId(), storagePassword16.getStoragePasswordId(), 16, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage17 = new StorageDAO(16, station0.getStationId(), storagePassword17.getStoragePasswordId(), 17, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage18 = new StorageDAO(17, station0.getStationId(), storagePassword18.getStoragePasswordId(), 18, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage19 = new StorageDAO(18, station0.getStationId(), storagePassword19.getStoragePasswordId(), 19, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage20 = new StorageDAO(19, station0.getStationId(), storagePassword20.getStoragePasswordId(), 20, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage21 = new StorageDAO(20, station0.getStationId(), storagePassword21.getStoragePasswordId(), 21, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage22 = new StorageDAO(21, station0.getStationId(), storagePassword22.getStoragePasswordId(), 22, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage23 = new StorageDAO(22, station0.getStationId(), storagePassword23.getStoragePasswordId(), 23, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage24 = new StorageDAO(23, station0.getStationId(), storagePassword24.getStoragePasswordId(), 24, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage25 = new StorageDAO(24, station0.getStationId(), storagePassword25.getStoragePasswordId(), 25, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage26 = new StorageDAO(25, station0.getStationId(), storagePassword26.getStoragePasswordId(), 26, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage27 = new StorageDAO(26, station0.getStationId(), storagePassword27.getStoragePasswordId(), 27, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage28 = new StorageDAO(27, station0.getStationId(), storagePassword28.getStoragePasswordId(), 28, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage29 = new StorageDAO(28, station0.getStationId(), storagePassword29.getStoragePasswordId(), 29, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage30 = new StorageDAO(29, station0.getStationId(), storagePassword30.getStoragePasswordId(), 30, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);

            StorageDAO storage31 = new StorageDAO(30, station1.getStationId(), storagePassword31.getStoragePasswordId(), 114, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage32 = new StorageDAO(31, station1.getStationId(), storagePassword32.getStoragePasswordId(), 115, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage33 = new StorageDAO(32, station1.getStationId(), storagePassword33.getStoragePasswordId(), 116, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage34 = new StorageDAO(33, station1.getStationId(), storagePassword34.getStoragePasswordId(), 117, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage35 = new StorageDAO(34, station1.getStationId(), storagePassword35.getStoragePasswordId(), 118, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage36 = new StorageDAO(35, station1.getStationId(), storagePassword36.getStoragePasswordId(), 119, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage37 = new StorageDAO(36, station1.getStationId(), storagePassword37.getStoragePasswordId(), 120, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage38 = new StorageDAO(37, station1.getStationId(), storagePassword38.getStoragePasswordId(), 121, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage39 = new StorageDAO(38, station1.getStationId(), storagePassword39.getStoragePasswordId(), 122, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage40 = new StorageDAO(39, station1.getStationId(), storagePassword40.getStoragePasswordId(), 123, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage41 = new StorageDAO(40, station1.getStationId(), storagePassword41.getStoragePasswordId(), 124, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage42 = new StorageDAO(41, station1.getStationId(), storagePassword42.getStoragePasswordId(), 125, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage43 = new StorageDAO(42, station1.getStationId(), storagePassword43.getStoragePasswordId(), 126, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage44 = new StorageDAO(43, station1.getStationId(), storagePassword44.getStoragePasswordId(), 127, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage45 = new StorageDAO(44, station1.getStationId(), storagePassword45.getStoragePasswordId(), 128, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage46 = new StorageDAO(45, station1.getStationId(), storagePassword46.getStoragePasswordId(), 129, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage47 = new StorageDAO(46, station1.getStationId(), storagePassword47.getStoragePasswordId(), 130, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage48 = new StorageDAO(47, station1.getStationId(), storagePassword48.getStoragePasswordId(), 131, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage49 = new StorageDAO(48, station1.getStationId(), storagePassword49.getStoragePasswordId(), 132, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage50 = new StorageDAO(49, station1.getStationId(), storagePassword50.getStoragePasswordId(), 133, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage51 = new StorageDAO(50, station1.getStationId(), storagePassword51.getStoragePasswordId(), 134, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage52 = new StorageDAO(51, station1.getStationId(), storagePassword52.getStoragePasswordId(), 135, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage53 = new StorageDAO(52, station1.getStationId(), storagePassword53.getStoragePasswordId(), 136, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage54 = new StorageDAO(53, station1.getStationId(), storagePassword54.getStoragePasswordId(), 137, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage55 = new StorageDAO(54, station1.getStationId(), storagePassword55.getStoragePasswordId(), 138, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage56 = new StorageDAO(55, station1.getStationId(), storagePassword56.getStoragePasswordId(), 139, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);
            StorageDAO storage57 = new StorageDAO(56, station1.getStationId(), storagePassword57.getStoragePasswordId(), 140, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage58 = new StorageDAO(57, station1.getStationId(), storagePassword58.getStoragePasswordId(), 141, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage59 = new StorageDAO(58, station1.getStationId(), storagePassword59.getStoragePasswordId(), 142, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage60 = new StorageDAO(59, station1.getStationId(), storagePassword60.getStoragePasswordId(), 143, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.BIG);

            StorageDAO storage61 = new StorageDAO(60, station2.getStationId(), storagePassword61.getStoragePasswordId(), 201, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage62 = new StorageDAO(61, station2.getStationId(), storagePassword62.getStoragePasswordId(), 202, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage63 = new StorageDAO(62, station2.getStationId(), storagePassword63.getStoragePasswordId(), 203, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage64 = new StorageDAO(63, station2.getStationId(), storagePassword64.getStoragePasswordId(), 204, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage65 = new StorageDAO(64, station2.getStationId(), storagePassword65.getStoragePasswordId(), 205, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage66 = new StorageDAO(65, station2.getStationId(), storagePassword66.getStoragePasswordId(), 206, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage67 = new StorageDAO(66, station2.getStationId(), storagePassword67.getStoragePasswordId(), 207, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage68 = new StorageDAO(67, station2.getStationId(), storagePassword68.getStoragePasswordId(), 208, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.SMALL);
            StorageDAO storage69 = new StorageDAO(68, station2.getStationId(), storagePassword69.getStoragePasswordId(), 209, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage70 = new StorageDAO(69, station2.getStationId(), storagePassword70.getStoragePasswordId(), 210, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);

            StorageDAO storage71 = new StorageDAO(70, station3.getStationId(), storagePassword71.getStoragePasswordId(), 301, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage72 = new StorageDAO(71, station3.getStationId(), storagePassword72.getStoragePasswordId(), 302, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage73 = new StorageDAO(72, station3.getStationId(), storagePassword73.getStoragePasswordId(), 303, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage74 = new StorageDAO(73, station3.getStationId(), storagePassword74.getStoragePasswordId(), 304, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage75 = new StorageDAO(74, station3.getStationId(), storagePassword75.getStoragePasswordId(), 305, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage76 = new StorageDAO(75, station3.getStationId(), storagePassword76.getStoragePasswordId(), 306, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage77 = new StorageDAO(76, station3.getStationId(), storagePassword77.getStoragePasswordId(), 307, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage78 = new StorageDAO(77, station3.getStationId(), storagePassword78.getStoragePasswordId(), 308, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage79 = new StorageDAO(78, station3.getStationId(), storagePassword79.getStoragePasswordId(), 309, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);
            StorageDAO storage80 = new StorageDAO(79, station3.getStationId(), storagePassword80.getStoragePasswordId(), 310, StorageStat.EMPTY, new Date(System.currentTimeMillis()), StorageSize.MID);

            storageDAORepository.save(storage1);
            storageDAORepository.save(storage2);
            storageDAORepository.save(storage3);
            storageDAORepository.save(storage4);
            storageDAORepository.save(storage5);
            storageDAORepository.save(storage6);
            storageDAORepository.save(storage7);
            storageDAORepository.save(storage8);
            storageDAORepository.save(storage9);
            storageDAORepository.save(storage10);
            storageDAORepository.save(storage11);
            storageDAORepository.save(storage12);
            storageDAORepository.save(storage13);
            storageDAORepository.save(storage14);
            storageDAORepository.save(storage15);
            storageDAORepository.save(storage16);
            storageDAORepository.save(storage17);
            storageDAORepository.save(storage18);
            storageDAORepository.save(storage19);
            storageDAORepository.save(storage20);
            storageDAORepository.save(storage21);
            storageDAORepository.save(storage22);
            storageDAORepository.save(storage23);
            storageDAORepository.save(storage24);
            storageDAORepository.save(storage25);
            storageDAORepository.save(storage26);
            storageDAORepository.save(storage27);
            storageDAORepository.save(storage28);
            storageDAORepository.save(storage29);
            storageDAORepository.save(storage30);
            storageDAORepository.save(storage31);
            storageDAORepository.save(storage32);
            storageDAORepository.save(storage33);
            storageDAORepository.save(storage34);
            storageDAORepository.save(storage35);
            storageDAORepository.save(storage36);
            storageDAORepository.save(storage37);
            storageDAORepository.save(storage38);
            storageDAORepository.save(storage39);
            storageDAORepository.save(storage40);
            storageDAORepository.save(storage41);
            storageDAORepository.save(storage42);
            storageDAORepository.save(storage43);
            storageDAORepository.save(storage44);
            storageDAORepository.save(storage45);
            storageDAORepository.save(storage46);
            storageDAORepository.save(storage47);
            storageDAORepository.save(storage48);
            storageDAORepository.save(storage49);
            storageDAORepository.save(storage50);
            storageDAORepository.save(storage51);
            storageDAORepository.save(storage52);
            storageDAORepository.save(storage53);
            storageDAORepository.save(storage54);
            storageDAORepository.save(storage55);
            storageDAORepository.save(storage56);
            storageDAORepository.save(storage57);
            storageDAORepository.save(storage58);
            storageDAORepository.save(storage59);
            storageDAORepository.save(storage60);
            storageDAORepository.save(storage61);
            storageDAORepository.save(storage62);
            storageDAORepository.save(storage63);
            storageDAORepository.save(storage64);
            storageDAORepository.save(storage65);
            storageDAORepository.save(storage66);
            storageDAORepository.save(storage67);
            storageDAORepository.save(storage68);
            storageDAORepository.save(storage69);
            storageDAORepository.save(storage70);
            storageDAORepository.save(storage71);
            storageDAORepository.save(storage72);
            storageDAORepository.save(storage73);
            storageDAORepository.save(storage74);
            storageDAORepository.save(storage75);
            storageDAORepository.save(storage76);
            storageDAORepository.save(storage77);
            storageDAORepository.save(storage78);
            storageDAORepository.save(storage79);
            storageDAORepository.save(storage80);

            OrderDAO order1 = makeOrderBean.exec(new RequestMakeOrderDTO(user1, storage1, station1));
            OrderDAO order2 = makeOrderBean.exec(new RequestMakeOrderDTO(user2, storage2, station1));
            OrderDAO order3 = makeOrderBean.exec(new RequestMakeOrderDTO(user2, storage3, station2));
            OrderDAO order4 = makeOrderBean.exec(new RequestMakeOrderDTO(user2, storage4, station3));
            OrderDAO order5 = makeOrderBean.exec(new RequestMakeOrderDTO(user4, storage5, station2));
            OrderDAO order6 = makeOrderBean.exec(new RequestMakeOrderDTO(user4, storage42, station0));
            OrderDAO order7 = makeOrderBean.exec(new RequestMakeOrderDTO(user5, storage43, station2));

            takeOrderBean.exec(new RequestTakeOrderDTO(order1, user3));
            takeOrderBean.exec(new RequestTakeOrderDTO(order1, user3));
            takeOrderBean.exec(new RequestTakeOrderDTO(order4, user3));
            takeOrderBean.exec(new RequestTakeOrderDTO(order3, user1));


            makeStoreBean.exec(new RequestStoreDTO(user1, storage10));
            makeStoreBean.exec(new RequestStoreDTO(user1, storage10));
            makeStoreBean.exec(new RequestStoreDTO(user2, storage11));
            makeStoreBean.exec(new RequestStoreDTO(user2, storage12));
            makeStoreBean.exec(new RequestStoreDTO(user2, storage31));
            makeStoreBean.exec(new RequestStoreDTO(user4, storage33));

        }
    }
}
