server:
  port: 0

spring:
  application:
    name: backend-service
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
#  profiles:
#    include: HIDDEN
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to postrofit -backend


#token:
#  expiration_time: 86400000
#  secret: userToken

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO
            nodeValue: ERROR
